name: WorkflowEngine - Build and Publish to Docker
on: 
  push:
    paths:
    - 'app/**'
    - '.github/workflows/challenge.yml'
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies 
      working-directory: ./app
      run: npm install 
