name: Delete old branches

on:
  schedule:
    #- cron: "0 0 * * *"
    - cron: "*/5 * * * *"

jobs:
  delete_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --prune && git fetch --all && git branch --remote
        
      - name: List branches older than 2 months
        run: |
          TWO_MONTHS_AGO=$(date --date="2 months ago" +%Y-%m-%d)
          git for-each-ref --format="%(refname:short) %(committerdate:short)" refs/remotes | while read branch date; do
              if [[ $date < $TWO_MONTHS_AGO && $branch != "main" && $branch != "develop" && $branch != "master" ]]; then
                  echo "Branch $branch is older than 2 months"
              fi
          done

      - name: Delete branches older than 2 months
        run: |
          TWO_MONTHS_AGO=$(date --date="2 months ago" +%Y-%m-%d)
          git for-each-ref --format="%(refname:short) %(committerdate:short)" refs/remotes | while read branch date; do
              if [[ ($date < $TWO_MONTHS_AGO) && ( $branch != "main" || $branch != "develop" || $branch != "master" )  ]]; then
                  echo "Deleting branch $branch"
                  git fetch --all
                  git branch --remote
                  git branch -d $branch
              fi
          done
