name: Delete old branches

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main
      - master

jobs:
  delete_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --prune

      - name: List branches older than 2 months
        run: |
          TWO_MONTHS_AGO=$(date --date="2 months ago" +%Y-%m-%d)
          git for-each-ref --format="%(refname:short)" refs/remotes | while read branch; do
              if [[ ($date < $TWO_MONTHS_AGO) &&  (($branch != "origin/main") && ($branch != "main") && ($branch != "origin/develop") && ($branch != "develop") && ($branch != "origin/master") && ($branch != "master")) ]]; then
                  echo "Branch ${branch#*/} is older than 2 months"
              fi
          done

      - name: Delete branches older than 2 months
        run: |
          TWO_MONTHS_AGO=$(date --date="2 months ago" +%Y-%m-%d)
          git for-each-ref --format="%(refname:short)" refs/remotes | while read branch; do
              if [[ ($date < $TWO_MONTHS_AGO) &&  (($branch != "origin/main") && ($branch != "main") && ($branch != "origin/develop") && ($branch != "develop") && ($branch != "origin/master") && ($branch != "master")) ]]; then
                  echo "Branch ${branch#*/} is older than 2 months"
                  git push origin --delete ${branch#*/}
              fi
          done
