name: Nodejs Application - Build and Publish to Docker
on: 
  push:
    paths:
    - '.github/workflows/nodejs-app.yml'
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        mongodb-version: [4.0, 4.2]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: test-rs

    - run: npm install
      working-directory: ./app

    - run: npm install nodemon
      working-directory: ./app

    - name: Publish to talk2toks/tradeling_challenge on Docker Hub 
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: talk2toks/tradeling_challenge
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./app/Dockerfile
        context: ./app/
        tag: "v1.0.0"